[project]
name = "edgedb-mcp"
version = "0.1.0"
description = "Model Context Protocol server that provides access to EdgeDB"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
 "edgedb>=2.2.0",
 "jinja2>=3.1.4",
 "mcp>=1.0.0",
]
[[project.authors]]
name = "deepbuzin"
email = "contactbuzin@gmail.com"

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.scripts]
edgedb-mcp = "edgedb_mcp:main"
